clone_depth: 5

artifacts:
  - path: bin\nim.exe

platform:
  - x64

before_build:
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S openssl-devel"
  - C:\msys64\usr\bin\bash -lc "pacman -Ql libopenssl"
  - C:\msys64\usr\bin\bash -lc "pacman -Ql openssl-devel"
  - C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S libcurl-devel libsqlite-devel pcre-devel ncurses-devel"

build_script:
  - SET PATH=C:\msys64\mingw64\bin;bin;%PATH%
  - gcc -v
  - git clone -q --depth 1 https://github.com/nim-lang/csources
  - cd csources
  - build64.bat
  - cd ..
  - nim c koch
  - koch boot
  - koch boot -d:release

before_test:
  - nim e install_nimble.nims
  - nimble update
  - nimble install zip
  - nimble install opengl
  - nimble install sdl1

test_script:
  - koch test all --pedantic
