platform:
  - x86
  - x64

build_script:
  - SET PATH=C:\msys64\mingw64\bin;%PATH%
  - git clone -q --depth 1 git://github.com/nim-lang/csources.git csources
  - cd csources
  - build.bat
  - cd ..
  - bin/nim koch
  - koch boot
