clone_depth: 5

artifacts:
  - path: bin\nim.exe

platform:
  - x64

before_build:
  - appveyor DownloadFile http://nim-lang.org/download/dlls.zip
  - 7z x dlls.zip

build_script:
  - SET PATH=C:\msys64\mingw64\bin;dlls;bin;%PATH%
  - gcc -v
  - git clone -q --depth 1 https://github.com/nim-lang/csources
  - cd csources
  - build64.bat
  - cd ..
  - nim c koch
  - koch boot
  - koch boot -d:release

before_test:
  - nim e install_nimble.nims
  - nimble update
  - nimble install zip

test_script:
  - koch test all --pedantic
